from aiogram.fsm.state import State, StatesGroup


class UserFlow(StatesGroup):
    waiting_for_op = State()
    recording_circle = State()
    reporting_circle = State()
    choosing_circle_gender = State()
    anon_setup_gender = State()
    anon_setup_age = State()
    reporting_anon = State()


class Admin(StatesGroup):
    main = State()
    op_management = State()
    add_channel_name = State()
    add_channel_url = State()
    add_channel_stage = State()
    add_channel_premium_target = State()
    add_channel_check_type = State()
    add_channel_chat_id = State()
    add_special_button_text = State()
    add_special_button_url = State()
    add_special_button_positions = State()
    add_ad_link_name = State()
    add_task_name = State()
    add_task_reward = State()
    add_task_url = State()
    add_task_check_type = State()
    add_task_chat_id = State()
    add_greeting_message = State()
    add_whitelist_user_id = State()
    select_whitelist_user_for_exclusion = State()
    wl_toggle = State()
    add_show_message = State()
    add_show_delay = State()
    add_show_target = State()
    add_show_n_delay = State()
    add_special_button_color = State()
    set_moderation_channel = State()
    edit_service_value = State()
    edit_op_limit_value = State()

    add_bait_circle_video = State()
    add_bait_circle_name = State()
    add_bait_circle_username = State()
    add_bait_circle_gender = State()
    add_bait_message_text = State()
    add_bait_message_button = State()
    add_bait_message_delay = State()
    edit_setting_value = State()
    ban_user_id = State()
    unban_user_id = State()
    add_admin_user_id = State()

    broadcast_message = State()
    broadcast_compose = State()
    broadcast_add_button = State()
    broadcast_confirm = State()

    greeting_compose = State()
    greeting_add_button = State()
